
import 'app_colors.dart';

class Globals {

  ///Substituir l'API Key
  static const apiKey = "hrthgrgsdfgsdrgsgsrgsdrgsrgdrgsdrg";

  static const examplePrompt = "{\r\n     \"model\": \"gpt-4-0613\",\r\n     \"messages\": [{\"role\": \"user\", \"content\": \"Dame un JSON correspondiente a \\\"LOS 5 MINERALES M\\u00C1S INFLUYENTES DE EUROPA Y AFRICA\\\". El JSON debe tener la siguiente estructura:\\r\\nArray con el numero de objetos especificado. Que cada objeto tenga solamente estos campos:\\r\\ntitle (String)\\r\\ndescription (String)\\r\\natribute (Float) ( [numerical_value] debe corresponder a un atributo. Este valor debe describir alg\\u00FAn atributo num\\u00E9rico del objeto. Por ejemplo, en caso de que los objetos sean deportes, este valor num\\u00E9rico puede corresponder a la dificultad o al porcentaje de personas que lo practican, en caso de que los objetos sean platos de comida, este valor podr\\u00EDa corresponder tambi\\u00E9n a la dificultad, al tiempo de preparaci\\u00F3n o por ejemplo, a una escala de frescura. El atributo debe ser el mismo para todos los objetos del array. No puede ser que el atributo de uno sea dificultad y de otro dureza)\\r\\n\\r\\nEl objeto seria algo as\\u00ED:\\r\\n[{\\\"title\\\":\\\"Tomate\\\", \\\"description\\\": \\\"El tomate es el mejor cultivo\\\", \\\"atribute\\\": {\\\"name\\\":\\\"Dulzura (escala del 1 al 10)\\\", \\\"value\\\": 6},\\r\\n{\\\"title\\\":\\\"Patata\\\", \\\"description\\\": \\\"Patatas para todo el mundo\\\", \\\"atribute\\\": {\\\"name\\\":\\\"Dulzura (escala del 1 al 10)\\\", \\\"value\\\": 4},\\r\\n(...)]\\r\\n\\r\\nMUY IMPORTANTE! NO DEBEN TODOS LOS OBJETOS DEBEN TENER EL MISMO ATRIBUTO. NO DEBE HABER ATRIBUTOS DIFERENTES ENTRE LOS DIFERENTES OBJETOS DEL ARRAY!\"}],\r\n     \"temperature\": 0.7\r\n   }";
  static const promptBefore = "{\r\n     \"model\": \"";
  static const promptMid = "\",\r\n     \"messages\": [{\"role\": \"user\", \"content\": \"Dame un JSON correspondiente a \\\"";
  static const promptAfter = "\\\". El JSON debe tener la siguiente estructura:\\r\\nArray con el numero de objetos especificado. Que cada objeto tenga solamente estos campos:\\r\\ntitle (String)\\r\\ndescription (String)\\r\\natribute (Float) ( [numerical_value] debe corresponder a un atributo. Este valor debe describir alg\\u00FAn atributo num\\u00E9rico del objeto. Por ejemplo, en caso de que los objetos sean deportes, este valor num\\u00E9rico puede corresponder a la dificultad o al porcentaje de personas que lo practican, en caso de que los objetos sean platos de comida, este valor podr\\u00EDa corresponder tambi\\u00E9n a la dificultad, al tiempo de preparaci\\u00F3n o por ejemplo, a una escala de frescura. El atributo debe ser el mismo para todos los objetos del array. No puede ser que el atributo de uno sea dificultad y de otro dureza)\\r\\n\\r\\nEl objeto seria algo as\\u00ED:\\r\\n[{\\\"title\\\":\\\"Tomate\\\", \\\"description\\\": \\\"El tomate es el mejor cultivo\\\", \\\"atribute\\\": {\\\"name\\\":\\\"Dulzura (escala del 1 al 10)\\\", \\\"value\\\": 6},\\r\\n{\\\"title\\\":\\\"Patata\\\", \\\"description\\\": \\\"Patatas para todo el mundo\\\", \\\"atribute\\\": {\\\"name\\\":\\\"Dulzura (escala del 1 al 10)\\\", \\\"value\\\": 4},\\r\\n(...)]\\r\\n\\r\\nMUY IMPORTANTE! NO DEBEN TODOS LOS OBJETOS DEBEN TENER EL MISMO ATRIBUTO. NO DEBE HABER ATRIBUTOS DIFERENTES ENTRE LOS DIFERENTES OBJETOS DEL ARRAY!\"}],\r\n     \"temperature\": 0.7\r\n   }";

  static const imageUrl = "https://www.applesfromny.com/wp-content/uploads/2020/06/SnapdragonNEW.png";
  static const testingResponse = "{\r\n  \"id\": \"chatcmpl-7fyCzftghWARYy75hXP4oifVQfeAN\",\r\n  \"object\": \"chat.completion\",\r\n  \"created\": 1690237245,\r\n  \"model\": \"gpt-4-0613\",\r\n  \"choices\": [\r\n    {\r\n      \"index\": 0,\r\n      \"message\": {\r\n        \"role\": \"assistant\",\r\n        \"content\": \"[\\n  {\\n    \\\"title\\\": \\\"Diamante\\\",\\n    \\\"description\\\": \\\"El diamante es uno de los minerales m\u00E1s influyentes de \u00C1frica, especialmente en pa\u00EDses como Botsuana, la Rep\u00FAblica Democr\u00E1tica del Congo y Sud\u00E1frica.\\\",\\n    \\\"atribute\\\": {\\n      \\\"name\\\": \\\"Dureza (escala de Mohs)\\\",\\n      \\\"value\\\": 10\\n    }\\n  },\\n  {\\n    \\\"title\\\": \\\"Oro\\\",\\n    \\\"description\\\": \\\"El oro es un mineral influyente tanto en Europa como en \u00C1frica, con la miner\u00EDa de oro siendo una industria importante en pa\u00EDses como Sud\u00E1frica, Ghana y Rusia.\\\",\\n    \\\"atribute\\\": {\\n      \\\"name\\\": \\\"Dureza (escala de Mohs)\\\",\\n      \\\"value\\\": 2.5\\n    }\\n  },\\n  {\\n    \\\"title\\\": \\\"Platino\\\",\\n    \\\"description\\\": \\\"El platino es otro mineral altamente influyente en \u00C1frica, particularmente en Sud\u00E1frica, que es el mayor productor mundial de este mineral.\\\",\\n    \\\"atribute\\\": {\\n      \\\"name\\\": \\\"Dureza (escala de Mohs)\\\",\\n      \\\"value\\\": 4.3\\n    }\\n  },\\n  {\\n    \\\"title\\\": \\\"Plomo\\\",\\n    \\\"description\\\": \\\"Europe, particularly Spain, is one of the largest producers of lead. This mineral plays a significant role in the European mining industry.\\\",\\n    \\\"atribute\\\": {\\n      \\\"name\\\": \\\"Dureza (escala de Mohs)\\\",\\n      \\\"value\\\": 1.5\\n    }\\n  },\\n  {\\n    \\\"title\\\": \\\"Cobre\\\",\\n    \\\"description\\\": \\\"El cobre es un mineral influyente en Europa, especialmente en pa\u00EDses como Polonia y Bulgaria. Tambi\u00E9n es un recurso importante en varios pa\u00EDses africanos como Zambia y la Rep\u00FAblica Democr\u00E1tica del Congo.\\\",\\n    \\\"atribute\\\": {\\n      \\\"name\\\": \\\"Dureza (escala de Mohs)\\\",\\n      \\\"value\\\": 3\\n    }\\n  }\\n]\"\r\n      },\r\n      \"finish_reason\": \"stop\"\r\n    }\r\n  ],\r\n  \"usage\": {\r\n    \"prompt_tokens\": 374,\r\n    \"completion_tokens\": 425,\r\n    \"total_tokens\": 799\r\n  }\r\n}\r\n";

}